export class Addressstudent {
  house_number:string;
  group:string;
  village:string;
  alley:string;
  street:string;
  subdistrict:string;
  district:string;
  province:string;
  post:number;
  address_now:number;
  house_number_n:string;
  village_n:string;
  alley_n:string;
  street_n:string;
  subdistrict_n:string;
  district_n:string;
  province_n:string;
  post_n:number;
  group_n:string;
}
