export class Parentstudent{
  id:number;
  student_idcard_p:string = '';
  prename_f:string = '';
  name_f:string = '';
  name_cen_f:string = '';
  surname_f:string = '';
  id_father:string = '';
  type_card_f:string = '';
  age_f:string = '';
  bloodgroup_f:string = '';
  job_f:string = '';
  salary_f:string = '';
  tel_f:string = '';
  house_number_f:string = '';
  group_f:string = '';
  village_f:string = '';
  alley_f:string = '';
  street_f:string = '';
  subdistrict_f:string = '';
  district_f:string = '';
  province_f:string = '';
  post_f:number;
  prename_m:string = '';
  name_m:string = '';
  name_cen_m:string = '';
  surname_m:string = '';
  id_mother:string = '';
  type_card_m:string = '';
  age_m:string = '';
  bloodgroup_m:string = '';
  job_m:string = '';
  salary_m:string = '';
  tel_m:string = '';
  house_number_m:string = '';
  group_m:string = '';
  village_m:string = '';
  alley_m:string = '';
  street_m:string = '';
  subdistrict_m:string = '';
  district_m:string = '';
  province_m:string = '';
  post_m:number ;
  parent:string = '';
  prename_p:string = '';
  name_p:string = '';
  name_cen_p:string = '';
  surname_p:string = '';
  id_parent:string = '';
  type_card_p:string = '';
  age_p:string = '';
  bloodgroup_p:string = '';
  job_p:string = '';
  salary_p:string = '';
  tel_p:string = '';
  house_number_p:string = '';
  group_p:string = '';
  village_p:string = '';
  alley_p:string = '';
  street_p:string = '';
  subdistrict_p:string = '';
  district_p:string = '';
  province_p:string = '';
  post_p:number;
  status_parent:string = '';
  student_parent:string = '';
  no_blood:number;
  no_brother:number;
  no_son:number;
  no_sister:number;
  no_son2:number;
  no_parent:number;
  no_study:number;
  no_job:number;
  no_house:number;
  student_job:string = '';
  student_money:string = '';
  parent_money:string = '';
  parent_total:string = '';
  parent_house:string = '';
  job_study:string = '';
  job_detail:string = '';
  total_study:string = '';
}
