export class Studentcore{
  student_id_card:number;
  student_id:number;
  student_major:string;
  student_class:string;
  student_room:string;
  prename:string;
  prename_eng:string;
  name_eng:string;
  name_cen_eng:string;
  surname_eng:string;
  birth_year:string;
  birth_month:string;
  birth_day:string;
  nickname:string;
  gender:string;
  bloodgroup:string;
  religion:string;
  origin:string;
  nationality:string;
  language:string;
  tel_s:string;
  email:string;
  name:string;
  name_cen:string;
  surname:string;
}
