export class StudentInformationCore{
  id : number;
  student_id : number;
  student_id_card: number;
  prename : string;
  name : string;
  name_cen : string;
  surname : string;
  sex : string;
  pic : string;
  id_number : string;
  birthday : string;
  religion : string;
  nationality : string;
  origin : string;
  house_number : string;
  bloc : string;
  street : string;
  road : string;
  sub_district : string;
  district : string;
  province : string;
  post : string;
  diabled : string;
  poor_person : string;
  etc : string;
  status : boolean;
  classroom_id : string;
  tel : string;
  score : string;
  email: string;
  blood_group: string;
  talent: string;
  distance_school: number;
  go_school: string;
  no_son: number;
  no_brother: number;
  no_he: number;
  no_she: number;
  no_parent: number;
  status_parent: string;
  total_parent: string;
  total_student: string;
  student_job: string;
  student_job_name: string;
  student_job_total: number;

}
