export class Talentstudent{
  student_idcard_t:string = '';
  final_school:string = '';
  final_class:string = '';
  avg_grade:string = '';
  f_subdistrict:string = '';
  f_district:string = '';
  f_province:string = '';
  like_subject1:string = '';
  like_subject2:string = '';
  like_subject3:string = '';
  like_subject4:string = '';
  unlike_subject1:string = '';
  unlike_subject2:string = '';
  unlike_subject3:string = '';
  unlike_subject4:string = '';
  talent:string = '';
  dream_job:string = '';
  because:string = '';
  read_write:string = '';
  understand:string = '';
}
